import type { FundingCandidate } from '@/lib/funding-scout/types'

/** Always included in every scan for Turkish PhD candidates — not subject to rotation limits. */
export const TURKEY_PRIORITY_OPPORTUNITIES: FundingCandidate[] = [
  {
    funder: 'TÜBİTAK',
    title: '2210-A Yurtiçi Doktora Burs Programı',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'TÜBİTAK national PhD scholarship for Turkish citizens pursuing doctorate in Turkey. Full stipend. Engineering, maritime, AI, shipbuilding. Apply before PhD start.',
    opportunityUrl: 'https://www.tubitak.gov.tr/tr/burslar/lisansustu-burs-programlari/2210-a-yurtici-doktora-burs-programi',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'TÜBİTAK',
    title: '2214-A Yurtdışı Doktora Araştırma Burs Programı',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'Turkish PhD students — funded research abroad (Netherlands, China co-supervision, joint PhD). Bilateral university agreements. Turkish citizens enrolled in domestic PhD.',
    opportunityUrl: 'https://www.tubitak.gov.tr/tr/burslar/lisansustu-burs-programlari/2214-a-yurtdisi-doktora-arastirma-burs-programi',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'TÜBİTAK',
    title: '2247 Sanayiye Yönelik Ulusal Doktora Programı',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'Industry-oriented national PhD programme. Turkish citizens. Engineering R&D including maritime, energy, AI.',
    opportunityUrl: 'https://www.tubitak.gov.tr/tr/destekler/sanayi/2247-sanayiye-yonelik-ulusal-doktora-programi',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'TÜBİTAK',
    title: '2209-A Üniversite Öğrencileri Araştırma Burs Programı (mezuniyet sonrası doktora hazırlık)',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'Research scholarship for university students — gateway to PhD. Turkish nationals.',
    opportunityUrl: 'https://www.tubitak.gov.tr/tr/burslar/lisansustu-burs-programlari',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'TÜBİTAK',
    title: '1001 Bilimsel ve Teknolojik Araştırma Projeleri',
    fundingType: 'project_grant',
    region: 'turkey',
    description: 'TÜBİTAK research project grant — PhD students often funded via supervisor project. Maritime, AI, engineering.',
    opportunityUrl: 'https://www.tubitak.gov.tr/tr/destekler/akademik/1001-bilimsel-ve-teknolojik-arastirma-projeleri-destekleme-programi',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'YÖK',
    title: '100/2000 Yurt Dışı Doktora Burs Programı',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'YÖK World Doctorate Scholarship — Turkish citizens for PhD abroad. Priority fields including engineering. Full funding.',
    opportunityUrl: 'https://1002000.yok.gov.tr/',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'YÖK',
    title: '100/2000 Öncelikli Alanlar Doktora Bursu',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'YÖK priority-field doctorate scholarship. Engineering, AI, maritime-related fields. Turkish nationals.',
    opportunityUrl: 'https://1002000.yok.gov.tr/',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'YÖK',
    title: 'Tez / Proje Destek Bursu (lisansüstü)',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'YÖK thesis and project support scholarships for graduate students including PhD candidates in Turkey.',
    opportunityUrl: 'https://www.yok.gov.tr/',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'KYK',
    title: 'KYK Lisansüstü Burs ve Kredi',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'Kredi ve Yurtlar Kurumu — graduate (yüksek lisans / doktora) scholarship and loan for Turkish students. Need-based and merit. Apply via e-Government.',
    opportunityUrl: 'https://www.kyk.gov.tr/',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'KYK',
    title: 'KYK Yurt ve Burs Başvurusu (doktora)',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'KYK dormitory and scholarship support for PhD students at Turkish universities. Annual application cycle.',
    opportunityUrl: 'https://www.tyk.gov.tr/kyk/ogrenci/burslar',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'Fulbright Turkey',
    title: 'Fulbright Doktora ve Araştırma Bursları',
    fundingType: 'fellowship',
    region: 'turkey',
    description: 'Fulbright Commission Turkey — PhD and research fellowships for Turkish citizens. US and international research.',
    opportunityUrl: 'https://fulbright.org.tr/burslar/',
    source: 'curated:turkey-priority',
    fullFunding: true,
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
  {
    funder: 'Mevlana',
    title: 'Mevlana Değişim Programı (doktora)',
    fundingType: 'phd_scholarship',
    region: 'turkey',
    description: 'Turkish higher education exchange — PhD mobility including partner universities abroad (Netherlands, China). Co-supervision mobility.',
    opportunityUrl: 'https://mevlana.yok.gov.tr/',
    source: 'curated:turkey-priority',
    priorityTier: 'turkey_national',
    listingKind: 'program_catalog',
  },
]

export function isTurkishCandidate(settings: { homeCountry?: string; citizenship?: string; regions?: string[] }): boolean {
  const c = (settings.homeCountry ?? settings.citizenship ?? 'TR').toUpperCase()
  if (c === 'TR' || c === 'TURKEY' || c === 'TÜRKİYE') return true
  return settings.regions?.includes('turkey') ?? false
}
