/** Shared domain vocabulary for job relevance and fit scoring. */

import { isRelatedEmployer } from '@/lib/job-agent/related-employers'

export const DOMAIN_ALIASES: Record<string, string[]> = {
  maritime: [
    'maritime',
    'shipping',
    'vessel',
    'ship',
    'fleet',
    'port',
    'marine',
    'naval',
    'offshore vessel',
    'classification society',
    'ais',
    'cargo',
    'container',
    'dnv',
    'lloyd',
    "lloyd's",
    'bureau veritas',
    'kongsberg',
    'wärtsilä',
    'wartsil',
    'man energy',
    'windward',
    'kpler',
    'marinetraffic',
    'spire maritime',
  ],
  offshore: [
    'offshore',
    'subsea',
    'oil and gas',
    'oil & gas',
    'rig',
    'platform',
    'fpso',
    'drilling',
    'wellhead',
    'rov',
    'umbilical',
    'mooring',
    'pipelay',
    'deepwater',
  ],
  energy: [
    'energy',
    'power',
    'utility',
    'utilities',
    'grid',
    'transmission',
    'distribution',
    'electricity',
    'oil',
    'gas',
    'petroleum',
    'lng',
    'pipeline',
    'refinery',
    'upstream',
    'downstream',
    'midstream',
    'power plant',
    'nuclear',
    'hydropower',
    'geothermal',
    'bioenergy',
    'decarbon',
    'net zero',
    'carbon',
    'emissions',
    'shell',
    ' bp ',
    'equinor',
    'totalenergies',
    'total energies',
    'chevron',
    'exxon',
    'conocophillips',
    'schlumberger',
    ' slb ',
    'halliburton',
    'baker hughes',
    'technip',
    'technipfmc',
    'saipem',
    'worley',
    'wood plc',
    'wood group',
    'fluor',
    'bechtel',
    'jacobs',
    'kbr',
    'petrofac',
    'modec',
    'enel',
    'iberdrola',
    ' rwe ',
    'vattenfall',
    ' edf ',
    'engie',
    'repsol',
    'statkraft',
    'national grid',
    'tennet',
    ' eon ',
    ' sse ',
    'centrica',
    'schneider',
    ' abb ',
    'siemens energy',
    'siemens gamesa',
    'siemens',
    'rolls royce',
    'rolls-royce',
    'bentley systems',
    'bentley',
    'ge vernova',
    'ge renewable',
    'hitachi energy',
    'emerson',
    'rockwell',
    'honeywell',
    'orsted',
    'ørsted',
    'nextera',
    'brookfield renewable',
    'enphase',
    'first solar',
    'sunrun',
  ],
  renewable_energy: [
    'renewable',
    'renewables',
    'solar',
    'green energy',
    'clean energy',
    'hydrogen',
    'battery storage',
    'energy storage',
    'photovoltaic',
    'pv ',
    'cleantech',
    'climate tech',
    'sustainability',
    'esg',
  ],
  wind: [
    'wind',
    'turbine',
    'offshore wind',
    'onshore wind',
    'vestas',
    'siemens gamesa',
    'nordex',
    'goldwind',
    'ge wind',
    'blade',
    'nacelle',
    'wind farm',
    'wind energy',
  ],
  engineering: [
    'engineering',
    'consultancy',
    'consultant',
    'consulting',
    'epc',
    'contractor',
    'arup',
    ' wsp ',
    'ramboll',
    'afry',
    'sweco',
    'fugro',
    ' bmt ',
    'naval architect',
    'civil engineering',
    'structural',
    'mechanical engineering',
    'project engineer',
    'design engineer',
    'systems engineer',
  ],
  digital_twin: [
    'digital twin',
    'simulation',
    'iot',
    'telemetry',
    'twins',
    'scada',
    'condition monitoring',
    'predictive maintenance',
    'asset performance',
  ],
  machine_learning: [
    'machine learning',
    'ml ',
    'deep learning',
    'neural',
    'pytorch',
    'tensorflow',
    'scikit',
    'mlops',
  ],
  data_science: [
    'data science',
    'analytics',
    'statistics',
    'data scientist',
    'bi developer',
    'business intelligence',
    'data analyst',
    'data engineer',
  ],
  ai: [' artificial intelligence', ' ai ', 'llm', 'genai', 'nlp', 'computer vision'],
  hci: ['hci', 'human-computer', 'ux research', 'usability', 'human factors'],
  research: ['phd', 'research', 'academic', 'r&d', 'postdoc', 'scientist', 'thesis'],
}

/** Always considered when scoring relevance — even if profile lists fewer domains. */
export const CORE_SEARCH_DOMAINS = [
  'maritime',
  'offshore',
  'energy',
  'renewable_energy',
  'wind',
  'engineering',
  'digital_twin',
  'machine_learning',
  'data_science',
  'ai',
  'research',
] as const

export const TECH_ROLE_RE =
  /\b(data scientist|data engineer|ml engineer|machine learning|research engineer|research scientist|applied scientist|ai engineer|software engineer|backend engineer|full.?stack|python developer|analytics engineer|quantitative|phd|scientist|developer|analyst)\b/i

export const INDUSTRY_SIGNAL_RE =
  /\b(energy|maritime|offshore|renewable|wind|solar|hydrogen|vessel|shipping|turbine|sensor|iot|predictive|maintenance|simulation|digital twin|geospatial|environmental|sustainability|power|grid|subsea|oil|gas|utilities|emissions|decarbon|cleantech|consulting|engineering)\b/i

export function termsForDomain(domain: string): string[] {
  const key = domain.toLowerCase()
  return DOMAIN_ALIASES[key] ?? [key.replace(/_/g, ' ')]
}

export function relevanceDomains(profileDomains: string[], preferenceDomains: string[]): string[] {
  return [...new Set([...CORE_SEARCH_DOMAINS, ...profileDomains, ...preferenceDomains])]
}

export function isKnownSectorCompany(company: string): boolean {
  if (isRelatedEmployer(company)) return true
  const hay = company.toLowerCase()
  const sectorTerms = [
    ...DOMAIN_ALIASES.energy,
    ...DOMAIN_ALIASES.maritime,
    ...DOMAIN_ALIASES.offshore,
    ...DOMAIN_ALIASES.wind,
    ...DOMAIN_ALIASES.renewable_energy,
    ...DOMAIN_ALIASES.engineering,
  ]
  return sectorTerms.some((term) => term.trim().length > 2 && hay.includes(term.trim()))
}

export { isRelatedEmployer, matchRelatedEmployer } from '@/lib/job-agent/related-employers'

export function isTechnicalRole(role: string): boolean {
  return TECH_ROLE_RE.test(role)
}

export function hasIndustrySignals(text: string): boolean {
  return INDUSTRY_SIGNAL_RE.test(text)
}
